#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use yii\helpers\ArrayHelper;
use yii\console\Application;

require __DIR__ . '/vendor/autoload.php';

defined('YII_DEBUG') or define('YII_DEBUG', env('YII_DEBUG', true));
defined('YII_ENV') or define('YII_ENV',  env('YII_ENV', 'dev'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = ArrayHelper::merge(
    require __DIR__ . '/config/base.php',
    require __DIR__ . '/config/console.php'
);

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
